---
- name: Check for kubectl
  stat:
    path: "{{ kubeconfig_path }}"
  register: kubectl

- name: Copy Kubernetes Secrets
  template:
    src: secrets.yml.tpl
    dest: /tmp/secrets.yml
    owner: root
    group: root
    mode: 0600
  register: k8s_secrets
  when: kubectl.stat.exists

- name: Apply Secrets
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: /tmp/secrets.yml
  when: k8s_secrets.changed
  ignore_errors: yes

- name: Remove secrets file from tmp directory
  become: yes
  file:
    path: /tmp/secrets.yml
    state: absent