---
- name: Clean the RKE2 Cluster Node
  import_playbook: clean_system.yml
  tags: [ 'never', 'clean_system' ]

- name: Configure the RKE2 Cluster
  import_playbook: create_cluster.yml
  tags: create_cluster

- name: Configure Monitoring
  import_playbook: deploy_monitoring.yml
  tags: deploy_monitoring

- name: Deploy Wordpress
  import_playbook: deploy_wordpress.yml
  tags: deploy_wordpress