---
- name: Clean the RKE2 Cluster Node
  import_playbook: clean.yml
  tags: [ 'never', 'clean_system' ]

- name: Configure the RKE2 Cluster
  import_playbook: cluster.yml
  tags: create_cluster

- name: Configure Monitoring
  import_playbook: monitoring.yml
  tags: deploy_monitoring