---
apiVersion: v1
kind: Service
metadata:
  name: chores-mysql
  namespace: chores
spec:
  selector:
    app: chores-mysql
  ports:
  - name: chores-mysql
    protocol: TCP
    port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chores-mysql
  namespace: chores
  labels:
    app: chores-mysql
spec:
  selector:
    matchLabels:
      app: chores-mysql
  template:
    metadata:
      labels:
        app: chores-mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chores-secret
              key: ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: chores-secret
              key: DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: chores-secret
              key: USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: chores-secret
              key: PASSWORD
        ports:
        - containerPort: 3306
          name: chores-mysql
        volumeMounts:
        - name: chores-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: chores-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: chores-mysql-pv-claim