---
- name: Include create_namespace playbook
  include_role:
    name: common
    tasks_from: create_namespace

- name: Include create_mount_directory playbook
  include_role:
    name: common
    tasks_from: create_mount_directory
  loop: "{{ directories }}"

- name: Apply Secrets
  include_role:
    name: secrets

- name: Include create_persistent_volume playbook
  include_role:
    name: common
    tasks_from: create_persistent_volume
  loop: "{{ persistent_volumes }}"

- name: Include create_persistent_volume_claim playbook
  include_role:
    name: common
    tasks_from: create_persistent_volume_claim
  loop: "{{ persistent_volume_claims }}"
