---
- name: Include create_namespace playbook
  include_role:
    name: common
    tasks_from: create_namespace

- name: Include create_mount_directory playbook
  include_role:
    name: common
    tasks_from: create_mount_directory
  with_dict: "{{ directoies }}"
