---
- name: Install samba
  ansible.builtin.package:
    name: samba
    state: present

- name: Append samba share config to smb.conf
  ansible.builtin.blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [share]
        path = /mnt/storage
        writeable = yes
        browseable = yes
        public = yes
        create mask = 0644
        directory mask = 0755
        force directory mode = 2770
    backup: yes
    state: present

- name: Create SMB Users
  ansible.builtin.shell: |
    (echo "{{ cluster_admin_password }}" ; echo "{{ cluster_admin_password }}") | smbpasswd -s -a {{ cluster_admin }}
  become: true
  no_log: true  # Optional:  Hide password from log


- name: Restart smb service
  ansible.builtin.service:
    name: smb
    state: restarted

- name: Restart nmb service
  ansible.builtin.service:
    name: nmb
    state: restarted