namespace: wordpress
directories:
  - path: /mnt/storage/wordpress/mysql
    mode: '0755'
    owner: nobody
    group: nogroup
  - path: /mnt/storage/wordpress/wordpress
    mode: '0777'
    owner: nobody
    group: nogroup
persistent_volumes:
  - name: mysql
    path: /mnt/storage/wordpress/mysql
    capacity: 10Gi
    accessModes: ReadWriteOnce
  - name: wordpress
    path: /mnt/storage/wordpress/wordpress
    capacity: 10Gi
    accessModes: ReadWriteOnce
persistent_volume_claims:
  - name: mysql-pv-claim
    storage: 5Gi
    accessModes: ReadWriteOnce
  - name: wordpress-pv-claim
    storage: 5Gi
    accessModes: ReadWriteOnce
network:
  - type: NodePort
    name: wordpress-service
    app: wordpress
    port_name: http
    port: 80
    targetport: 80
  - type: ClusterIP
    name: mysql
    app: mysql
    port_name: database
    port: 3306
    targetport: 3306