namespace: wordpress
directories:
  - path: /mnt/storage/wordpress/mysql
    mode: '0755'
    owner: nobody
    group: nogroup
  - path: /mnt/storage/wordpress/wordpress
    mode: '0777'
    owner: nobody
    group: nogroup
persistent_volumes:
  - name: mysql
    path: /mnt/storage/wordpress/mysql
    capacity: 10Gi
  - name: wordpress
    path: /mnt/storage/wordpress/wordpress
    capacity: 10Gi
