---
- name: Include create_namespace playbook
  include_role:
    name: common
    tasks_from: create_namespace

- name: Add MetalLB Helm repository
  kubernetes.core.helm_repository:
    name: stable
    repo_url: https://metallb.github.io/metallb

- name: Update helm repositories
  ansible.builtin.command: helm repo update

- name: Set the current context to the metallb-system namespace
  vars:
    command: "{{ kubectl_path }} config set-context --current --namespace metallb-system --kubeconfig {{ kubeconfig_path }}"
  shell: "{{ command }}"

- name: Deploy latest version of MetalLB via Helm
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig_path }}"
    name: metallb
    chart_ref: stable/metallb
    release_namespace: metallb-system
    
- name: Fetch IP address of Host
  vars:
    command: "hostname -I | awk '{print $1}'"
  shell: "{{ command }}"
  register: host_ip

- name: Create MetalLB IPAddressPool from template
  become: true
  template:
    src: ipaddresspool_metallb.j2
    dest: /tmp/ipaddresspool_metallb.yml

- name: Apply MetalLB IPAddressPool
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: /tmp/ipaddresspool_metallb.yml

- name: Apply MetalLB L2Advertisement
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: l2advertisement_metallb.yml