---
- name: Download cleanup script
  shell: curl -sLO https://github.com/rancherlabs/support-tools/raw/master/extended-rancher-2-cleanup/extended-cleanup-rancher2.sh

- name: Execute cleanup script
  shell: bash extended-cleanup-rancher2.sh -f

- name: Reboot the node
  shell: reboot