apiVersion: apps/v1
kind: Deployment
metadata:
  name: choresdev
  namespace: choresdev
  labels:
    app: choresdev
spec:
  selector:
    matchLabels:
      app: choresdev
  template:
    metadata:
      labels:
        app: choresdev
    spec:
      containers:
      - image: deemack/chores-java:1.12
        imagePullPolicy: Always
        volumeMounts:
          - name: config-volume
            mountPath: /config
            readOnly: true
        name: choresdev
        ports:
        - containerPort: 8080
          name: choresdev
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:/config/application.properties
        envFrom:
        - configMapRef:
            name: choresdev-datasource-config
      volumes:
      - name: config-volume
        configMap:
          name: spring-datasource-config