---

- name: Get UUID of Storage Drive
  shell: lsblk -no uuid /dev/sda | xargs
  register: uuid

- name: UUID of Storage Device
  debug:
    var: "{{ uuid.stdout }}"

- name: Mount Storage Device by UUID
  mount:
    path: /mnt/storage
    src: UUID={{ uuid.stdout }}
    fstype: ntfs
    opts: permissions,locale=en_US.utf8
    state: mounted
    dump: 0
    passno: 2

- name: Fetch IP address of Host
  vars:
    command: "hostname -I | awk '{print $1}'"
  shell: "{{ command }}"
  register: host_ip

- name: Host IP
  debug:
    var: host_ip.stdout

- name: Create manifests folder
  file:
    path: /var/lib/rancher/rke2/server/manifests
    state: directory

- name: Copy nginx-config file
  copy:
    src: config-nginx.yaml
    dest: /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml

- name: Install RKE2 from binary
  shell: curl -sfL https://get.rke2.io |INSTALL_RKE2_TYPE=server  sh -

- name: Enable rke2-server service
  shell: systemctl enable rke2-server.service

- name: Start the rke2-server service
  shell: systemctl start rke2-server.service

- name: Copy kubeconfig
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /home/dave/rke2/rke2.yaml
    owner: dave
    group: wheel
    remote_src: true
  become: yes
  become_user: root

- name: Export PATH
  shell: export PATH=$PATH:/var/lib/rancher/rke2/bin
  become: yes
  become_user: dave

- name: Export KUBCONFIG
  shell: export KUBECONFIG=/home/dave/rke2/rke2.yaml

- name: Append PATH to bashrc
  lineinfile:
    path: /home/dave/.bashrc
    line: export PATH=$PATH:/var/lib/rancher/rke2/bin
    create: yes

- name: Append KUBECONFIG to bashrc
  lineinfile:
    path: /home/dave/.bashrc
    line: export KUBECONFIG=/home/dave/rke2/rke2.yaml
    create: yes

- name: Refresh bashrc
  shell: source /home/dave/.bashrc
  become: yes
  become_user: dave

- name: Download OpenEBS yaml 
  get_url:
    url: https://openebs.github.io/charts/openebs-operator.yaml
    dest: /home/dave/rke2/playbooks/roles/cluster/files/openebs-operator.yaml

- name: Install OpenEBS Local Storage Solution
  kubernetes.core.k8s:
    kubeconfig: /home/dave/rke2/rke2.yaml
    state: present
    src: /home/dave/rke2/playbooks/roles/cluster/files/openebs-operator.yaml