---

- name: Get UUID of Storage Drive
  shell: lsblk -no uuid /dev/sda | xargs
  register: uuid

- name: UUID of Storage Device
  debug:
    var: "{{ uuid.stdout }}"

- name: Mount Storage Device by UUID
  mount:
    path: /mnt/storage
    src: UUID={{ uuid.stdout }}
    fstype: ntfs
    opts: permissions,locale=en_US.utf8
    state: mounted
    dump: 0
    passno: 2

- name: Fetch IP address of Host
  vars:
    command: "hostname -I | awk '{print $1}'"
  shell: "{{ command }}"
  register: host_ip

- name: Host IP
  debug:
    var: host_ip.stdout

- name: Create manifests folder
  file:
    path: /var/lib/rancher/rke2/server/manifests
    state: directory

- name: Copy nginx-config file
  copy:
    src: config-nginx.yaml
    dest: /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml

- name: Install RKE2 from binary
  shell: curl -sfL https://get.rke2.io |INSTALL_RKE2_TYPE=server  sh -

- name: Enable rke2-server service
  shell: systemctl enable rke2-server.service

- name: Start the rke2-server service
  shell: systemctl start rke2-server.service

- name: Export PATH
  shell: export PATH=$PATH:/var/lib/rancher/rke2/bin

- name: Export KUBCONFIG
  shell: export KUBECONFIG=/etc/rancher/rke2/rke2.yaml

- name: Append PATH to bashrc
  shell: echo "export PATH=$PATH:/var/lib/rancher/rke2/bin" >> $HOME/.bashrc

- name: Append KUBECONFIG to bashrc
  shell: echo "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml"  >> $HOME/.bashrc 

- name: Refresh bashrc
  shell: source ~/.bashrc

- name: Install OpenEBS Local Storage Solution
  shell: kubectl apply -f https://openebs.github.io/charts/openebs-operator.yaml



