---
- name: Include create_namespace playbook
  include_role:
    name: common
    tasks_from: create_namespace

- name: Create Secrets
  include_role:
    name: secrets
    tasks_from: main

- name: Include create_mount_directory playbook
  include_role:
    name: common
    tasks_from: create_mount_directory
  loop: "{{ directories }}"

- name: Include create_persistent_volume playbook
  include_role:
    name: common
    tasks_from: create_persistent_volume
  loop: "{{ persistent_volumes }}"

- name: Include create_persistent_volume_claim playbook
  include_role:
    name: common
    tasks_from: create_persistent_volume_claim
  loop: "{{ persistent_volume_claims }}"

- name: Deploy xwiki database
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: "{{ namespace }}"
    api_version: v1
    state: present
    src: deployment_postgres.yml

- name: Deploy xwiki App
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: "{{ namespace }}"
    api_version: v1
    state: present
    src: deployment_xwiki.yml

- name: Include create_service playbook
  include_role:
    name: common
    tasks_from: create_service
  loop: "{{ network }}"

- name: Check for xwiki backup
  become: true
  find:
    paths: /mnt/storage/xwiki/backup
    file_type: any
  register: backup

#- name: Restore from backup when available
#  when: backup.matched != 0
#  include_tasks: restore_backup.yml
#  tags: xwiki_restore

- name: Copy backup script
  copy:
    src: xwiki_backup.sh
    dest: /tmp
    mode: u+rwx
    owner: k8sadmin
    group: k8sadmin

- name: Copy restore script
  copy:
    src: xwiki_restore.sh
    dest: /tmp
    mode: u+rwx
    owner: k8sadmin
    group: k8sadmin

- name: check user
  become: yes
  become_user: "{{ cluster_admin }}"
  become_method: su
  become_flags: '--login'
  vars:
    ansible_become_pass: "{{ cluster_admin_password }}"
  shell: whoami

- name: Restore from backup when available
  when: backup.matched != 0
  become: yes
  become_user: "{{ cluster_admin }}"
  become_method: su
  become_flags: '--login'
  vars:
    ansible_become_pass: "{{ cluster_admin_password }}"
  command:
    cmd: /tmp/xwiki_restore.sh
  tags: xwiki_restore

- name: Copy xwiki backup script to Host
  become: true
  copy:
    src: /tmp/xwiki_backup.sh
    dest: /usr/sbin/
    mode: 0755
    remote_src: yes

- name: Create cronjob to backup the xwiki database each night
  ansible.builtin.cron:
    name: "xwiki database backup"
    minute: "0"
    hour: "0"
    user: root
    job: "/usr/sbin/xwiki_backup.sh"

- name: Restart xwiki pgsql deployment
  command:
    cmd: "{{ kubectl_path }} --kubeconfig {{ kubeconfig_path }} rollout restart -n xwiki deployment/xwiki-postgres"

- name: Restart xwiki deployment
  command:
    cmd: "{{ kubectl_path }} --kubeconfig {{ kubeconfig_path }} rollout restart -n xwiki deployment/xwiki"