- name: Wait for xwiki pod to become ready
  command:
    cmd: '"{{ kubectl_path }}" --kubeconfig "{{ kubeconfig_path }}" wait --namespace=xwiki --for=condition=Ready pods --selector app=xwiki-postgres --timeout=600s'
  register: xwiki_pod_ready

- debug: var=xwiki_pod_ready.stdout_lines

- name: Get xwiki backups
  find:
    paths: "/mnt/storage/xwiki/backup/"
  register: found_files

- name: Get latest backup file
  set_fact:
    latest_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"

- debug:
    msg: latest backup file is "{{ latest_file.path }}"

- name: Copy latest xwiki database backup file to postgres pod
  copy:
    src: "{{ latest_file.path }}"
    dest: /mnt/storage/xwiki/postgres/
    remote_src: true

- name: Restart xwiki pgsql deployment
  command:
    cmd: '"{{ kubectl_path }}" --kubeconfig "{{ kubeconfig_path }}" rollout restart -n xwiki deployment/xwiki-postgres'

- name: Wait for xwiki pod to become ready again
  command:
    cmd: '"{{ kubectl_path }}" --kubeconfig "{{ kubeconfig_path }}" wait --namespace=xwiki --for=condition=Ready pods --selector app=xwiki-postgres --timeout=600s'
  register: xwiki_pod_ready

- debug: var=xwiki_pod_ready.stdout_lines

- name: Get xwiki database pod name
  command:
    cmd: '"{{ kubectl_path }}" --kubeconfig "{{ kubeconfig_path }}" get pods -n xwiki -l=app=xwiki-postgres --sort-by=.metadata.creationTimestamp -o jsonpath="{.items[0].metadata.name}" --no-headers
  register: pod_pgsql

- debug:
    msg: xwiki db pod is "{{ pod_pgsql.stdout }}"

- name: Drop xwiki database
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: xwiki
    pod: "{{ pod_pgsql.stdout }}"
    #container: xwiki-postgres
    command: dropdb -U xwiki xwiki -f

- name: Create xwiki database
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: xwiki
    pod: "{{ pod_pgsql.stdout }}"
    container: xwiki-postgres
    command: createdb -U xwiki xwiki

- name: Get xwiki database latest backup
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: xwiki
    pod: "{{ pod_pgsql.stdout }}"
    #container: xwiki-postgres
    command: ls -u /var/lib/postgresql/data/*xwikibackup* | head -1
  register: backup_postgres

- debug:
    msg: Restoring xwiki from backup "{{ backup_postgres.stdout }}"

- name: Restore xwiki database
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: xwiki
    pod: "{{ pod_pgsql.stdout }}"
    container: pgsql
    command: pg_restore -U xwiki -d xwiki "{{ backup_postgres.stdout }}"

- name: Restart xwiki pgsql deployment
  vars:
    command: '"{{ kubectl_path }}" --kubeconfig "{{ kubeconfig_path }}" rollout restart -n xwiki deployment/xwiki-postgres'
    shell: "{{ command }}"

#- name: Restart xwiki pgsql deployment
#  command:
#    cmd: "{{ kubectl_path }}" --kubeconfig "{{ kubeconfig_path }}" rollout restart -n xwiki deployment/xwiki-postgres"

- name: Restart xwiki deployment
  command:
    cmd: "{{ kubectl_path }}" --kubeconfig "{{ kubeconfig_path }}" rollout restart -n xwiki deployment/xwiki-postgres