---
- name: Wait for xwiki pod to become ready
  shell: /bin/bash -c "{{ kubectl_path }} wait --namespace=xwiki --for=condition=Ready pods --selector app=xwiki-postgres --timeout=600s"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: xwiki_pod_ready

- debug: var=xwiki_pod_ready.stdout_lines

