namespace: xwiki
directories:
  - path: /mnt/storage/xwiki/postgres
    mode: '0755'
    owner: nobody
    group: nogroup
  - path: /mnt/storage/xwiki/xwiki
    mode: '0777'
    owner: nobody
    group: nogroup
persistent_volumes:
  - name: postgres
    path: /mnt/storage/xwiki/postgres
    capacity: 10Gi
  - name: xwiki
    path: /mnt/storage/xwiki/xwiki
    capacity: 10Gi
persistent_volume_claims:
  - name: postgres-pv-claim
    storage: 10Gi
  - name: xwiki-pv-claim
    storage: 10Gi
network:
  - type: NodePort
    name: xwiki-service
    app: xwiki
    port_name: http
    port: 8080
    targetport: 8080
  - type: ClusterIP
    name: xwiki-postgres
    app: xwiki-postgres
    port_name: database
    port: 5432
    targetport: 5432