---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Get UUID of Storage Drive
  shell: lsblk -no uuid /dev/sda | xargs
  register: uuid

- name: UUID of Storage Device
  debug:
    var: "{{ uuid.stdout }}"

- name: Create mount directory for SSD
  file:
    path: /mnt/storage
    state: directory
    mode: '0755'

- name: Mount Storage Device by UUID
  mount:
    path: /mnt/storage
    src: UUID={{ uuid.stdout }}
    fstype: ntfs
    opts: permissions,locale=en_US.utf8
    state: mounted
    dump: 0
    passno: 2

- name: Create Rancher manifests folder
  file:
    path: /var/lib/rancher/rke2/server/manifests
    state: directory

- name: Copy nginx-config file
  copy:
    src: config-nginx.yml
    dest: /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yml

- name: Install kubernetes pre-requisites
  pip:
    name:
      - kubernetes

- name: Install RKE2 from binary
  shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
  tags: rke2_script

- name: Enable and Start the rke2-server service
  service:
    name: rke2-server.service
    state: started
    enabled: true

- name: Sleep for 600 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 600
  tags: cluster_sleep






# - name: Create kubeconfig file
#   copy:
#     dest: "{{ lookup('env', 'HOME') }}/.kube/config"
#     content: |
#       apiVersion: v1
#       clusters:
#       - cluster:
#           certificate-authority-data: "{{ ca_data.stdout }}"
#           server: "{{ cluster_server }}"
#         name: "{{ cluster_name }}"
#       contexts:
#       - context:
#           cluster: "{{ cluster_name }}"
#           user: admin-user
#         name: admin-context
#       current-context: admin-context
#       kind: Config
#       preferences: {}
#       users:
#       - name: admin-user
#         user:
#           token: "{{ admin_token.stdout }}"
#   tags: admin_user



#- name: Copy kubeconfig to 
#  copy:
#    src: /etc/rancher/rke2/rke2.yaml
#    dest: ~/rke2.yaml
#    remote_src: true
#  become: true
#  become_user: root




- name: Take ownership of kubeconfig
  shell: "chown -R {{ cluster_admin }}:{{ cluster_admin }} /etc/rancher/rke2/rke2.yaml"

- name: Export KUBCONFIG
  shell: export KUBECONFIG="{{ kubeconfig_path }}"

- name: Export PATH
  shell: export PATH=$PATH:/var/lib/rancher/rke2/bin  

- name: Append PATH to bashrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: export PATH=$PATH:/var/lib/rancher/rke2/bin
    create: true

- name: Append KUBECONFIG to bashrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: export KUBECONFIG="{{ kubeconfig_path }}"
    create: true

- name: Refresh bashrc
  shell: source "{{ lookup('env', 'HOME') }}/.bashrc"

- name: Create a Kubernetes user
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: new-user
        namespace: default


- name: Create admin ServiceAccount
  shell: "{{ kubectl_path }} --kubeconfig {{ kubeconfig_path }} create serviceaccount admin-user -n kube-system"

# - name: Bind ServiceAccount to cluster-admin role
#   shell: kubectl create clusterrolebinding admin-user-binding --clusterrole=cluster-admin --serviceaccount=kube-system:admin-user
#   when: create_sa.changed
#   tags: admin_user
#   become: true
#   become_user: root

# - name: Get admin-user token
#   shell: kubectl -n kube-system get secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}') -o jsonpath="{.data.token}" | base64 --decode
#   register: admin_token
#   tags: admin_user
#   become: true
#   become_user: root

# - name: Get certificate authority data
#   shell: kubectl config view --raw -o jsonpath='{.clusters[0].cluster.certificate-authority-data}'
#   register: ca_data
#   tags: admin_user
#   become: true
#   become_user: root

- name: Download OpenEBS yml
  get_url:
    url: https://openebs.github.io/charts/openebs-operator.yaml
    dest: /tmp/openebs-operator.yml

- name: Install OpenEBS Local Storage Solution
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: /tmp/openebs-operator.yml


#- name: Reboot the node
#  shell: reboot