---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Get UUID of Storage Drive
  shell: lsblk -no uuid /dev/sda | xargs
  register: uuid

- name: UUID of Storage Device
  debug:
    var: "{{ uuid.stdout }}"

- name: Create mount direcotry for SSD
  file:
    path: /mnt/storage
    state: directory
    mode: '0755'

- name: Mount Storage Device by UUID
  mount:
    path: /mnt/storage
    src: UUID={{ uuid.stdout }}
    fstype: ntfs
    opts: permissions,locale=en_US.utf8
    state: mounted
    dump: 0
    passno: 2

- name: Create Rancher manifests folder
  file:
    path: /var/lib/rancher/rke2/server/manifests
    state: directory

- name: Copy nginx-config file
  copy:
    src: config-nginx.yml
    dest: /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yml

- name: Install kubernetes pre-requisites
  pip:
    name:
      - kubernetes

- name: Install RKE2 from binary
  shell: curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
  tags: rke2_script

- name: Enable and Start the rke2-server service
  service:
    name: rke2-server.service
    state: started
    enabled: true

- name: Sleep for 600 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 600
  tags: cluster_sleep

- name: Copy kubeconfig
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: ~/rke2.yaml
    remote_src: true
  become: true
  become_user: root

- name: Export PATH
  shell: export PATH=$PATH:/var/lib/rancher/rke2/bin

- name: Export KUBCONFIG
  shell: export KUBECONFIG=~/rke2.yaml

- name: Append PATH to bashrc
  lineinfile:
    path: ~/.bashrc
    line: export PATH=$PATH:/var/lib/rancher/rke2/bin
    create: true

- name: Append KUBECONFIG to bashrc
  lineinfile:
    path: ~/.bashrc
    line: export KUBECONFIG=~/rke2.yaml
    create: true

- name: Refresh bashrc
  shell: source ~/.bashrc

- name: Download OpenEBS yml
  get_url:
    url: https://openebs.github.io/charts/openebs-operator.yaml
    dest: /tmp/openebs-operator.yml

- name: Install OpenEBS Local Storage Solution
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    state: present
    src: /tmp/openebs-operator.yml
    remote_src: true
  become: true
  become_user: root

#- name: Reboot the node
#  shell: reboot