---
- name: Create Persistent Volume yaml
  become: true
  template:
    src: create_persistent_volume.j2
    dest: /tmp/create_persistent_volume.yml
  vars:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    capacity: "{{ item.capacity }}"

- name: Create Persistent Volume
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: "{{ namespace }}"
    api_version: v1
    state: present
    src: /tmp/create_persistent_volume.yml