---
- name: Create Service yaml
  become: true
  template:
    src: create_service.j2
    dest: /tmp/create_service.yml
  vars:
    type: "{{ item.type }}"
    name: "{{ item.name }}"
    app: "{{ item.app }}"
    traffic: "{{ item.traffic }}"
    port: "{{ item.port }}"
    targetport: "{{ item.targetport }}"
    #nodeport: "{{ item.nodeport }}"
    nodeport: "{{ nodeports | selectattr('application', 'match', item.name) | map(attribute='port') | first }} | default('')"

- name: Create Service
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: "{{ namespace }}"
    api_version: v1
    state: present
    src: /tmp/create_service.yml
