---
apiVersion: v1
kind: Service
metadata:
  name: xwiki-postgres
spec:
  selector:
    app: xwiki-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xwiki-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xwiki-postgres
  template:
    metadata:
      labels:
        app: xwiki-postgres
    spec:
      containers:
      - name: xwiki-postgres
        image: postgres
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: xwiki-postgres-secret
                key: POSTGRES_DB # value: "xwiki"  # Replace with your PostgreSQL database name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: xwiki-postgres-secret
                key: POSTGRES_USER # value: "xwiki"  # Replace with your PostgreSQL username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: xwiki-postgres-secret
                key: POSTGRES_PASSWORD # value: "xwiki"  # Replace with your PostgreSQL password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-pv-claim
          mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: postgres-pv-claim
        persistentVolumeClaim:
          claimName: postgres-pv-claim