---
- name: Clean the RKE2 Cluster Node
  import_playbook: clean.yaml
  tags: [ 'never', 'clean' ]

- name: Configure the RKE2 Cluster
  import_playbook: cluster.yaml
  tags: cluster

- name: Configure Dashboard
  import_playbook: dashboard.yaml
  tags: dashboard